name: qf_tv
description: QueueFlow — Native Linux TV display terminal

publish_to: 'none'
version: 1.0.20+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  dart_pusher_channels: ^1.2.3
  audioplayers: ^6.1.0
  video_player: ^2.9.2
  webview_flutter: ^4.13.0
  webview_win_floating: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
